### ISSUE TITLE
Stylelint Plugin

### ISSUE THREAD

**Issue by stramel** [bartveneman/constyble#13]
It would be amazing to have a PostCSS plugin for this tool!

**Comment by bartveneman** [comment]
This is built on top of https://github.com/projectwallace/css-analyzer, which is built on top of postcss. How would you envision Constyble as a postcss plugin?

**Comment by stramel** [comment]
Sorry, I think I meant stylelint. Just a way to analyze and keep these things in check during development.

**Comment by bartveneman** [comment]
So your use case would be to have it as a stylelint plugin to that it can run in your editor/IDE while developing?

Constyble is meant to run on your *generated* CSS, so after all PostCSS plugins, preprocessors etc. are done. I wonder what value Constyble would add in an editor. But I'm open for suggestions! 😄
